name: hello ops girls dev pipeline
run-name: dev-ci

env:
  AWS_ACCOUNT: "494526681395"
  AWS_REGION: "ap-southeast-1"

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: aws-auth
        uses: "./.github/actions/aws-auth"

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/aws-auth"
